# Generated by Django 5.2.8 on 2025-12-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_datosfisicos_fecha_datosfisicos_imc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='membresia',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
