# Generated by Django 5.2.8 on 2025-12-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_membresia_comprobante_membresia_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevoCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('bibliografia', models.CharField(max_length=250)),
                ('especialidad', models.CharField(max_length=50)),
            ],
        ),
    ]
