# Generated by Django 5.2.6 on 2025-12-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_nuevocoach'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='coach',
            old_name='especialiad',
            new_name='especialidad',
        ),
    ]
