# Generated by Django 5.2.6 on 2025-12-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='claseprogramada',
            name='cupos',
            field=models.IntegerField(default=20),
        ),
    ]
