# Generated by Django 5.2.6 on 2025-12-05 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_claseprogramada_cupos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.claseprogramada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registro')),
            ],
        ),
    ]
