# Generated by Django 5.2.6 on 2025-12-05 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_reservaclase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.claseprogramada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registro')),
            ],
        ),
    ]
