# Generated by Django 5.2.6 on 2025-12-05 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_asistencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claseprogramada',
            old_name='cupos',
            new_name='cupos_disponibles',
        ),
    ]
