# Generated by Django 5.2.6 on 2025-12-05 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_cupos_claseprogramada_cupos_disponibles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.registro'),
        ),
        migrations.CreateModel(
            name='ReservaInvitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Reservado', max_length=20)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.claseprogramada')),
            ],
        ),
    ]
