# Generated by Django 6.0 on 2025-12-06 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_pago_usuario_reservainvitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.registro'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ReservaInvitado',
        ),
    ]
