# Generated by Django 5.2.6 on 2025-12-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_pago_usuario_delete_reservainvitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='clases_disponibles',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
